language: c
script: make && make travis && ./sslsplit -V
matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libssl-dev libevent-dev check
    - os: osx
      before_install:
        - brew install libevent
        - brew install check
